debian: change the way of installing python-pip
Run into this error `ImportError: cannot import name IncompleteRead` because of python pip version in debian packages